---
title: "Plotting global models outputs"
author: "Camilla Novaglio"
date: "12/10/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

# load data  

Load global ISIMIP2b model data (now stored in DKRZ, gem48 and local - will need to all be moved to local) 

```{r load CMIP5}

rm(list=ls())
# source("/data/home/camillan/dbpm/plotMaps.R")
source("/Users/nov017/R-projects/CMIP5vsCMIP6/R/Funcs_plot.R")
library('ncdf4')

# data 
input_loc <- "/Users/nov017/fishmip_outputs/marine-fishery_global_ISIMIP2b/"
save_loc <- "/Users/nov017/R-projects/CMIP5vsCMIP6/figs/"

# variables 
cmip<-c("CMIP5", "CMIP6")
mod <- c("APECOSM", "BOATS", "DBEM", "DBPM","EcoOcean", "MACROECOLOGICAL") # FEISTY & ZooMSS possibly coming - EcoTroph might be only CMIP6
protocol <- c("picontrol","historical", "future")
future<-c("SSP126", "SSP585")
var <- c("tcb","tpb", "bp30cm", "bp30to90cm", "bp90cm")

# APECOSM ----
h_yearsA <- "1950_2005"
f_yearsA<- "2006_2100"
outputA<-"monthly"
oaA<-"no-oa"

# BOATS ----
h_yearsB <- "1971_2005"
f_yearsB<- "2006_2099"
outputB<-"monthly"
oaB<-"no-oa"

# DBEM ----
h_yearsD <- "1951_2005"
f_yearsD<- "2006_2099"
outputD<-"annual"
oaD<-"oa"

# DBPM ----
h_yearsDB <- "1950_2005"
f_yearsDB<- "2006_2100"
outputDB<-"monthly"
oaDB<-"no-oa"

# EcoOcean ----  
h_yearsE <- "1971_2005"
f_yearsE<- "2006_2100"
outputE<-"monthly"
oaE<-"no-oa"

# macroecological ----  
h_yearsM <- "1950_2005"
f_yearsM<- "2006_2100"
outputM<-"annual"
oaM<-"no-oa"

# extract data ---- 
# consider only ipsl and tcb 

h_years <-c(h_yearsA, h_yearsB, h_yearsD, h_yearsDB, h_yearsE, h_yearsM)
f_years <-c(f_yearsA, f_yearsB, f_yearsD, f_yearsDB, f_yearsE, f_yearsM)
output <-c(outputA, outputB, outputD, outputDB, outputE, outputM)
oa <-c(oaA, oaB, oaD, oaDB, oaE, oaM)

data126<-list()
dim<-list() # dim of the future - just to check 
# data585<-list()

for (i in 1:length(mod)){

  hist <- stack(paste0(input_loc, mod[i], "/ipsl-cm5a-lr/", protocol[2],"/", tolower(mod[i]), "_ipsl-cm5a-lr_nobc_hist_wo-diaz_no-fishing_",oa[i],"_",var[1],"_global_", output[i], "_", h_years[i], ".nc4"))
  fut126 <- stack(paste0(input_loc, mod[i], "/ipsl-cm5a-lr/", protocol[3], "/", tolower(mod[i]), "_ipsl-cm5a-lr_nobc_rcp2p6_wo-diaz_no-fishing_",oa[i],"_",var[1],"_global_",output[i], "_",f_years[i],".nc4"))
 all126 <- list(hist = hist, fut = fut126)
 
 data126[[i]]<-all126
 names(data126)[[i]]<-mod[[i]]
 dim[[i]]<-dim(fut126)
 names(dim)[[i]]<-mod[[i]]
  
 rm(all126)
 
}

data126_CMIP5<-data126

# NOTE <- DBEM dimension is doubled - 0.5 grid cell resolution? NEEDS FIXING
# delete from all variables for now 
# data126$DBEM<-NULL
# mod <- c("APECOSM", "BOATS", "DBPM","EcoOcean", "MACROECOLOGICAL") # "EcoTroph", "FEISTY", "ZooMSS")
# h_years <-c(h_yearsA, h_yearsB, h_yearsDB, h_yearsE, h_yearsM)
# f_years <-c(f_yearsA, f_yearsB, f_yearsDB, f_yearsE, f_yearsM)
# output <-c(outputA, outputB, outputDB, outputE, outputM)
# oa <-c(oaA, oaB, oaDB, oaE, oaM)

```

Plot global ISIMIP2b model outputs

```{r map CMIP5}

# consider ssp126

map<-list()
#  ts <-list()

for (i in 1:length(data126)){ 

  # map of change
  clim <- c(-50, 50)
  
  # reference years
  refFirstYear<-(1990-as.numeric(substr(h_years[i], start = 1, stop = 4)))
  refLastYear<-(2090-as.numeric(substr(f_years[i], start = 1, stop = 4)))
  if(output[i]=="monthly"){
    refFirstYear = refFirstYear*12
    refLastYear = refLastYear*12
  }
  
  tit <- paste0(mod[i], " IPSL ", future[1], " ", var[1]," (1990s-2090s Change ", cmip[1], ")")
  map[[i]] <- plotGlobalChange(data126[[i]], tit, world_sf, clim, refFirstYear, refLastYear, output[i])
  names(map)[[i]]<-mod[[i]]
  
  # # trends 
  # tit <- paste0(mod[i], " IPSL ", future[1], " ", var[1]," (Change relative to 1990s ", cmip[1], ")")
  # date = seq(as.Date(paste0(substr(h_years[i], start = 1, stop = 4),"-1-1")), as.Date(paste0(substr(f_years[i], start = 6, stop = 9),"-12-1")), by = ifelse(output[i]=="monthly","month","year"))
  # ts[[i]] <- plotTimeseries(data126[[i]], tit, date)
  # names(ts)[[i]]<-mod[[i]]
  
}

map_CMIP5<-map

```

Load global ISIMIP3b model data (now stored in DKRZ, gem48 and local - will need to all be moved to local) 

```{r load CMIP6}

# data 
input_loc <- "/Users/nov017/fishmip_outputs/marine-fishery_global_ISIMIP3b/"

# variables 
mod <- c("APECOSM", "BOATS", "DBEM", "DBPM","EcoOcean", "MACROECOLOGICAL", "EcoTroph", "FEISTY", "ZooMSS") # all would be this 
mod <- c("MACROECOLOGICAL", "ZooMSS") # need to download DBPM, FEISTY, and BOATS

# APECOSM ----
# h_yearsA <- "1950_2005"
# f_yearsA<- "2006_2100"
# outputA<-"monthly"


# BOATS ----
# h_yearsB <- "1971_2005"
# f_yearsB<- "2006_2099"
# outputB<-"monthly"


# DBEM ----
# h_yearsD <- "1951_2005"
# f_yearsD<- "2006_2099"
# outputD<-"annual"


# DBPM ----
# dbpm_ipsl_cm6a_lr_nobc_historical_nat_default_tcb_global_montly_1850_2014.nc4
# dbpm_ipsl_cm6a_lr_nobc_ssp126_nat_default_tcb_global_montly_2015_2100.nc4
# h_yearsDB <- "1850_2014"
# f_yearsDB<- "2015_2100"
# outputDB<-"monthly"
# extensionDB <-".nc4"

# EcoOcean ----  
# h_yearsE <- "1971_2005"
# f_yearsE<- "2006_2100"
# outputE<-"monthly"
# oaE<-"no-oa"

# macroecological ----  
# macroecological_ipsl-cm6a-lr_nobc_historical_nat_default_tcb_global_annual_1950_2014.nc
# macroecological_ipsl-cm6a-lr_nobc_ssp126_nat_default_tcb_global_annual_2015-2100.nc
h_yearsM <- "1950_2014"
f_yearsM<- "2015_2100"
outputM<-"annual"
extensionM<-".nc"

# EcoTroph ----  
# h_yearsEC <- "1950_2005"
# f_yearsEC<- "2006_2100"
# outputEC<-"annual"

# FEISTY ----  
# h_yearsF <- "1950_2005"
# f_yearsF<- "2006_2100"
# outputF<-"annual"


# ZooMSS ----  
# zoomss_ipsl-cm6a-lr_nobasd_historical_nat_default_tcb_global_annual_1950_2014.nc
# zoomss_ipsl-cm6a-lr_nobasd_ssp126_nat_default_tcb_global_annual_2015_2100.nc
# zoomss_ipsl-cm6a-lr_nobasd_ssp585_nat_default_tcb_global_annual_2015_2100.nc
h_yearsZ <- "1950_2014"
f_yearsZ<- "2015_2100"
outputZ<-"annual"
extensionZ<-".nc4"

# extract data ---- 
# consider only ipsl and tcb 

h_years <-c(h_yearsM, h_yearsZ)
f_years <-c(f_yearsM, f_yearsZ)
output <-c(outputM,outputZ)
extension <-c(extensionM, extensionZ)

data126<-list()
dim<-list() # dim of the future - just to check 
# data585<-list()

for (i in 1:length(mod)){

  i =1
  hist <- stack(paste0(input_loc, mod[i], "/ipsl-cm5a-lr/", protocol[2],"/", tolower(mod[i]), "_ipsl-cm6a-lr_nobc_historical_nat_default_",var[1],"_global_", output[i], "_", h_years[i], extension[i]))

  fut126 <- stack(paste0(input_loc, mod[i], "/ipsl-cm5a-lr/", protocol[3], "/", tolower(mod[i]), "_ipsl-cm6a-lr_nobc_ssp126_nat_default_",var[1],"_global_",output[i], "_",f_years[i],extension[i]))

 # add together input data
 all126 <- list(hist = hist, fut = fut126)
 
 data126[[i]]<-all126
 names(data126)[[i]]<-mod[[i]]
 dim[[i]]<-dim(fut126)
 names(dim)[[i]]<-mod[[i]]
  
 rm(all126)
 
}

data126_CMIP6<-data126
```

Plot global ISIMIP3b model outputs

```{r plot CMIP6}

# consider ssp126

map<-list()
#  ts <-list()

for (i in 1:length(data126)){ 

  # map of change
  clim <- c(-50, 50)
  
  # reference years
  refFirstYear<-(1990-as.numeric(substr(h_years[i], start = 1, stop = 4)))
  refLastYear<-(2090-as.numeric(substr(f_years[i], start = 1, stop = 4)))
  if(output[i]=="monthly"){
    refFirstYear = refFirstYear*12
    refLastYear = refLastYear*12
  }
  
  tit <- paste0(mod[i], " IPSL ", future[1], " ", var[1]," (1990s-2090s Change ", cmip[2], ")")
  map[[i]] <- plotGlobalChange(data126[[i]], tit, world_sf, clim, refFirstYear, refLastYear, output[i])
  names(map)[[i]]<-mod[[i]]
  
  # # trends 
  # tit <- paste0(mod[i], " IPSL ", future[1], " ", var[1]," (Change relative to 1990s ", cmip[2], ")")
  # date = seq(as.Date(paste0(substr(h_years[i], start = 1, stop = 4),"-1-1")), as.Date(paste0(substr(f_years[i], start = 6, stop = 9),"-12-1")), by = ifelse(output[i]=="monthly","month","year"))
  # ts[[i]] <- plotTimeseries(data126[[i]], tit, date)
  # names(ts)[[i]]<-mod[[i]]
  
}

map_CMIP6<-map
```

put them all together 

```{r multipanel plot}

# multimodel for SSP ----

library(patchwork)

layout <- "
AB
CD
E#
F#
G#
H#
#I
"

pt<-map_CMIP5$DBPM + map_CMIP6$DBPM + 
    map_CMIP5$MACROECOLOGICAL + map_CMIP6$MACROECOLOGICAL+  
    map_CMIP5$DBEM +
    map_CMIP5$APECOSM + 
    map_CMIP5$EcoOcean + 
    map_CMIP5$BOATS+ 
    map_CMIP6$ZooMSS + # zooMMS
  plot_layout(design = layout)

pt<-pt + plot_annotation(
  title = 'Change in total consumer biomass 1990s-2090s, IPSL SSP585 CMIP5 vs CMIP6
  ',
  # subtitle = 'These are preliminary maps of available global models outputs considering the ISPL ssp585 scenario only', 
  theme = theme(plot.title = element_text(size = 28)))
                # plot.subtitle = element_text(size = 25)))

# pdf("IPSL_CMIP5vsCMIP5_summary.pdf", height=20, width=20) # ssp126, ssp585, trends ssp585 
tiff("IPSL_CMIP5vsCMIP5_summary.tiff", height=30, width=20, units ='in', res=300)
pt 
dev.off()

# multimodel for SSP ----

# detailed plots 
# pdf("IPSL_CMIP5.pdf", height=30, width=20) # ssp126, ssp585, trends ssp585 
tiff("IPSL_CMIP5.tiff", height=10, width=20, units ='in', res=300)
(map_cmip5$DBPM+map_cmip5$DBPM+ts_cmip5$DBPM)/ # dbpm # this should be ssp126 vs ssp585 so need to run both above    
  (map_cmip5$MACROECOLOGICAL+map_cmip5$MACROECOLOGICAL+ts_cmip5$MACROECOLOGICAL)  
dev.off()

```