---
title: "Plotting global models inputs"
author: "Camilla Novaglio"
date: "02/02/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

# TO DO 

# Load libraries for netcdf and define variables

```{r load CMIP5}

rm(list=ls())
library(grid)
library(zoo)
library(viridis)
library(tidyr)
library(dplyr)

source("/Users/camillan/R-projects/CMIP5vsCMIP6/R/HelperScripts.r")
source("/Users/camillan/R-projects/CMIP5vsCMIP6/R/Funcs_maps.r")

# saving outputs location  
save_loc <- "/Users/camillan/Dropbox/CMIP5vsCMIP6/figs/"

# variables - TO CHANGE 
cmip<-c("CMIP5", "CMIP6")
protocol <- c("picontrol","historical", "future")
future<-c("SSP126", "SSP585")

```

# load libraries for plotting and define criteria 

```{r}

# Define color/legend limits 
main_plot_colour_values_tos = c(0,30) # C and following Ryan paper  

# for CMIP6.... units checked by checking max and min in 2030 for each variable # MAX are too high for all variables ...   num_dp = 0 inside the plotting function can be used to regulate the digits
# main_plot_colour_values_pp = c(1.7e-09,3e-06) # mol m-2 s-1 # ryan paper is in mg C m-2 d-1
# main_plot_colour_values_phyto = c(0.014, 0.37) # mol m-2 # ryan paper is in mg C m-2
# main_plot_colour_values_zoo = c(0.0031,0.53) # mol m-2 # ryan paper is in mg C m-2
main_plot_colour_values_pp = c(1e-09,5e-07) # mol m-2 s-1 # ryan paper is in mg C m-2 d-1
main_plot_colour_values_phyto = c(0, 0.3) # mol m-2 # ryan paper is in mg C m-2
main_plot_colour_values_zoo = c(0,0.5) # mol m-2 # ryan paper is in mg C m-2
delta_plot_colour_values = c(-50,50)

# define a color scheme 
colour_scheme1 <- c(low = 'white', mid = "skyblue1",  high = 'royalblue1') # for statistics - e.g model mean, SD and agreement
colour_scheme2 <- c(low = 'red', mid = "white",  high = 'royalBlue1') # for % changes - either increasing or decreasing 
colour_scheme3 <- c("#fdb863", "#f7f7f7","#b2abd2") # for delta plots (% change between cmips) # purple to yellow shades
colour_scheme4 <- c(low = '#e0ecf4', mid = "#9ebcda",  high = '#8856a7') # for inputs values # shades of blue to purple?? 
colour_scheme4 <- c(low = 'white', mid = "#9ebcda",  high = '#8856a7') # for inputs values # shades of blue to purple?? 

# Download and process world outline
library(sf)
library(rnaturalearth)
library("rgeos")
world <- ne_countries(scale = "medium", returnclass = "sf")
robCRS <- CRS("+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs")
world_sf <- st_transform(world, crs = st_crs(robCRS)) # Convert to different CRS

```

# load ISIMIP2b inputs 

```{r}

# extract data IPSL ---- 

directory = "/Users/camillan/fishmip_inputs/marine-fishery_global_ISIMIP2b/IPSL_CM5A_LR/"

variable_to_extract <-c("to", "pp", "phy", "zoo")

yearmonth1<- as.yearmon("1990-01")
yearmonth2<- as.yearmon("1999-01") # yearly values

yearmonth1_fut<- as.yearmon("2090-01")
yearmonth2_fut<- as.yearmon("2099-01")

data_ipsl_CMIP5<-list()

for (i in 1:length(variable_to_extract)){

  # the variable is temperature,extract adn convert from K to C
  if(variable_to_extract[i] == "to"){
    
    filename<-paste0(variable_to_extract[i], ".nc4.zs.rgrd.v3.historical1_19500101_20051231_1Y.nc4")
    hist<- averageEnvironmentalCDF(directory, filename , variable_to_extract[i], yearmonth1, yearmonth2, average_whole_period = TRUE, convert_to_kg_km = FALSE, ipsl = TRUE, hist = TRUE)
    # from k to C
    hist$fishvar<-hist$fishvar - 273.15 # can be done later on if this is going to be merged with the loop below
    hist$data_units<-"C"
  
    filename<-paste0(variable_to_extract[i],".nc4.zs.rgrd.v3.rcp261_20060101_21001231_1Y.nc4")
    fut126<-averageEnvironmentalCDF(directory, filename , variable_to_extract[i], yearmonth1_fut, yearmonth2_fut, average_whole_period = TRUE, convert_to_kg_km = FALSE, ipsl = TRUE, hist = FALSE)
    fut126$fishvar<-fut126$fishvar - 273.15
    fut126$data_units<-"C"
  
    filename<-paste0(variable_to_extract[i],".nc4.zs.rgrd.v3.rcp851_20060101_21001231_1Y.nc4")
    fut585<- averageEnvironmentalCDF(directory, filename , variable_to_extract[i], yearmonth1_fut, yearmonth2_fut, average_whole_period = TRUE, convert_to_kg_km = FALSE, ipsl = TRUE, hist = FALSE)
    fut585$fishvar<-fut585$fishvar - 273.15
    fut126$data_units<-"C"
  
    fut585_2030<-averageEnvironmentalCDF(directory, filename , variable_to_extract[i], as.yearmon("2030-01"), as.yearmon("2030-01"), average_whole_period = FALSE, convert_to_kg_km = FALSE, ipsl = TRUE, hist = FALSE) # mean annual temp in 2030
    fut585_2030<-fut585_2030$fishvar[,]
    fut585_2030<-fut585_2030 - 273.15
    fut126$data_units<-"C"
  
  }else{ # # the variable is other than temperature, extract both small and large PP, phy or zoo and sum the size classes
    
      filename<-paste0("s",variable_to_extract[i], ".nc4.zint.rgrd.v3.historical1_19500101_20051231_1Y.nc4")
      histS<- averageEnvironmentalCDF(directory, filename , paste0("s", variable_to_extract[i]), yearmonth1, yearmonth2, average_whole_period = TRUE, convert_to_kg_km = FALSE, ipsl = TRUE, hist = TRUE)
      filename<-paste0("l",variable_to_extract[i], ".nc4.zint.rgrd.v3.historical1_19500101_20051231_1Y.nc4")
      histL<- averageEnvironmentalCDF(directory, filename , paste0("l", variable_to_extract[i]), yearmonth1, yearmonth2, average_whole_period = TRUE, convert_to_kg_km = FALSE, ipsl = TRUE, hist = TRUE)
      hist<-histS
      hist$fishvar<-hist$fishvar+histL$fishvar 
 
      filename<-paste0("s",variable_to_extract[i],".nc4.zint.rgrd.v3.rcp26.1_20060101_21001231_1Y.nc4")
      fut126S<-averageEnvironmentalCDF(directory, filename , paste0("s", variable_to_extract[i]), yearmonth1_fut, yearmonth2_fut, average_whole_period = TRUE, convert_to_kg_km = FALSE, ipsl = TRUE, hist = FALSE)
      filename<-paste0("l",variable_to_extract[i],".nc4.zint.rgrd.v3.rcp26.1_20060101_21001231_1Y.nc4")
      fut126L<-averageEnvironmentalCDF(directory, filename , paste0("l", variable_to_extract[i]), yearmonth1_fut, yearmonth2_fut, average_whole_period = TRUE, convert_to_kg_km = FALSE, ipsl = TRUE, hist = FALSE)
      fut126<-fut126S
      fut126$fishvar<-fut126$fishvar+fut126L$fishvar 
      
      filename<-paste0("s",variable_to_extract[i],".nc4.zint.rgrd.v3.rcp85.1_20060101_21001231_1Y.nc4")
      fut585S<-averageEnvironmentalCDF(directory, filename , paste0("s", variable_to_extract[i]), yearmonth1_fut, yearmonth2_fut, average_whole_period = TRUE, convert_to_kg_km = FALSE, ipsl = TRUE, hist = FALSE)
      fut585_2030S<-averageEnvironmentalCDF(directory, filename , paste0("s", variable_to_extract[i]), as.yearmon("2030-01"), as.yearmon("2030-01"), average_whole_period = FALSE, convert_to_kg_km = FALSE, ipsl = TRUE, hist = FALSE)
      fut585_2030S<-fut585_2030S$fishvar[,]
      filename<-paste0("l",variable_to_extract[i],".nc4.zint.rgrd.v3.rcp85.1_20060101_21001231_1Y.nc4")
      fut585L<-averageEnvironmentalCDF(directory, filename , paste0("l", variable_to_extract[i]), yearmonth1_fut, yearmonth2_fut, average_whole_period = TRUE, convert_to_kg_km = FALSE, ipsl = TRUE, hist = FALSE)
      fut585_2030L<-averageEnvironmentalCDF(directory, filename , paste0("l", variable_to_extract[i]), as.yearmon("2030-01"), as.yearmon("2030-01"), average_whole_period = FALSE, convert_to_kg_km = FALSE, ipsl = TRUE, hist = FALSE)
      fut585_2030L<-fut585_2030L$fishvar[,]
  
      fut585<-fut585S
      fut585$fishvar<-fut585$fishvar+fut585L$fishvar 
  
      fut585_2030<-fut585_2030S + fut585_2030L
    
  }
  
  diff_2p6 = fut126$fishvar / hist$fishvar * 100 - 100
  diff_8p5 = fut585$fishvar / hist$fishvar * 100 - 100
  
  data_ipsl_CMIP5[[i]]<-list(hist = hist, fut126 = fut126, fut585_2030 = fut585_2030, fut585 = fut585, diff_2p6 = diff_2p6, diff_8p5 = diff_8p5)
  names(data_ipsl_CMIP5)[[i]]<-variable_to_extract[[i]]
  
  rm(hist, fut126, fut585, fut585_2030, diff_2p6, diff_8p5)
  
}

names(data_ipsl_CMIP5)


# extract data GFDL ---- 

directory = "/Users/camillan/fishmip_inputs/marine-fishery_global_ISIMIP2b/GFDL_ESM2M/"

variable_to_extract <-c("to", "pp", "phy", "zoo")
# the variable inside the netcdf is called differently than the variable in the file name.  
variable_to_extract2 <-c("TO_ZS", "PP_ZINT", "PHY_ZINT", "ZOO_ZINT")

data_gfdl_CMIP5<-list()

for (i in 1:length(variable_to_extract)){

  # the variable is temperature,extract adn convert from K to C
  if(variable_to_extract[i] == "to"){
    
    filename<-paste0(variable_to_extract[i], "_gfdl-esm2m_historical_zs_annual_195001-200512.nc4")
    hist<- averageEnvironmentalCDF(directory, filename , variable_to_extract2[i], yearmonth1, yearmonth2, average_whole_period = TRUE, convert_to_kg_km = FALSE, ipsl = FALSE, hist = TRUE)
    # from k to C
    hist$fishvar<-hist$fishvar - 273.15 # can be done later on if this is going to be merged with the loop below
    hist$data_units<-"C"
  
    filename<-paste0(variable_to_extract[i],"_gfdl-esm2m_rcp26_zs_annual_200601-210012.nc4")
    fut126<-averageEnvironmentalCDF(directory, filename , variable_to_extract2[i], yearmonth1_fut, yearmonth2_fut, average_whole_period = TRUE, convert_to_kg_km = FALSE, ipsl = FALSE, hist = FALSE)
    fut126$fishvar<-fut126$fishvar - 273.15
    fut126$data_units<-"C"
  
    filename<-paste0(variable_to_extract[i],"_gfdl-esm2m_rcp85_zs_annual_200601-210012.nc4")
    fut585<- averageEnvironmentalCDF(directory, filename , variable_to_extract2[i], yearmonth1_fut, yearmonth2_fut, average_whole_period = TRUE, convert_to_kg_km = FALSE, ipsl = FALSE, hist = FALSE)
    fut585$fishvar<-fut585$fishvar - 273.15
    fut126$data_units<-"C"
  
    fut585_2030<-averageEnvironmentalCDF(directory, filename , variable_to_extract2[i], as.yearmon("2030-01"), as.yearmon("2030-01"), average_whole_period = FALSE, convert_to_kg_km = FALSE, ipsl = FALSE, hist = FALSE) # mean annual temp in 2030
    fut585_2030<-fut585_2030$fishvar[,]
    fut585_2030<-fut585_2030 - 273.15
    fut126$data_units<-"C"
  
  }else{ # # the variable is other than temperature, extract both small and large PP, phy or zoo and sum the size classes
    
      filename<-paste0("s",variable_to_extract[i], "_gfdl-esm2m_historical_zint_annual_195001-200512.nc4")
      histS<- averageEnvironmentalCDF(directory, filename , paste0("S", variable_to_extract2[i]), yearmonth1, yearmonth2, average_whole_period = TRUE, convert_to_kg_km = FALSE, ipsl = FALSE, hist = TRUE)
      filename<-paste0("l",variable_to_extract[i], "_gfdl-esm2m_historical_zint_annual_195001-200512.nc4")
      histL<- averageEnvironmentalCDF(directory, filename , paste0("L", variable_to_extract2[i]), yearmonth1, yearmonth2, average_whole_period = TRUE, convert_to_kg_km = FALSE, ipsl = FALSE, hist = TRUE)
      hist<-histS
      hist$fishvar<-hist$fishvar+histL$fishvar 
 
      filename<-paste0("s",variable_to_extract[i],"_gfdl-esm2m_rcp26_zint_annual_200601-210012.nc4")
      fut126S<-averageEnvironmentalCDF(directory, filename , paste0("S", variable_to_extract2[i]), yearmonth1_fut, yearmonth2_fut, average_whole_period = TRUE, convert_to_kg_km = FALSE, ipsl = FALSE, hist = FALSE)
      filename<-paste0("l",variable_to_extract[i],"_gfdl-esm2m_rcp26_zint_annual_200601-210012.nc4")
      fut126L<-averageEnvironmentalCDF(directory, filename , paste0("L", variable_to_extract2[i]), yearmonth1_fut, yearmonth2_fut, average_whole_period = TRUE, convert_to_kg_km = FALSE, ipsl = FALSE, hist = FALSE)
      fut126<-fut126S
      fut126$fishvar<-fut126$fishvar+fut126L$fishvar 
      
      filename<-paste0("s",variable_to_extract[i],"_gfdl-esm2m_rcp85_zint_annual_200601-210012.nc4")
      fut585S<-averageEnvironmentalCDF(directory, filename , paste0("S", variable_to_extract2[i]), yearmonth1_fut, yearmonth2_fut, average_whole_period = TRUE, convert_to_kg_km = FALSE, ipsl = FALSE, hist = FALSE)
      fut585_2030S<-averageEnvironmentalCDF(directory, filename , paste0("S", variable_to_extract2[i]), as.yearmon("2030-01"), as.yearmon("2030-01"), average_whole_period = FALSE, convert_to_kg_km = FALSE, ipsl = FALSE, hist = FALSE)
      fut585_2030S<-fut585_2030S$fishvar[,]
      filename<-paste0("l",variable_to_extract[i],"_gfdl-esm2m_rcp85_zint_annual_200601-210012.nc4")
      fut585L<-averageEnvironmentalCDF(directory, filename , paste0("L", variable_to_extract2[i]), yearmonth1_fut, yearmonth2_fut, average_whole_period = TRUE, convert_to_kg_km = FALSE, ipsl = FALSE, hist = FALSE)
      fut585_2030L<-averageEnvironmentalCDF(directory, filename , paste0("L", variable_to_extract2[i]), as.yearmon("2030-01"), as.yearmon("2030-01"), average_whole_period = FALSE, convert_to_kg_km = FALSE, ipsl = FALSE, hist = FALSE)
      fut585_2030L<-fut585_2030L$fishvar[,]
  
      fut585<-fut585S
      fut585$fishvar<-fut585$fishvar+fut585L$fishvar 
  
      fut585_2030<-fut585_2030S + fut585_2030L
    
  }
  
  diff_2p6 = fut126$fishvar / hist$fishvar * 100 - 100
  diff_8p5 = fut585$fishvar / hist$fishvar * 100 - 100
  
  data_gfdl_CMIP5[[i]]<-list(hist = hist, fut126 = fut126, fut585_2030 = fut585_2030, fut585 = fut585, diff_2p6 = diff_2p6, diff_8p5 = diff_8p5)
  names(data_gfdl_CMIP5)[[i]]<-variable_to_extract[[i]]
  
  rm(hist, fut126, fut585, fut585_2030, diff_2p6, diff_8p5)
  
}

names(data_gfdl_CMIP5)

```

# Plot ISIMIP2b inputs

```{r map CMIP6}

# flip matrix

fliplr_matrix<- function(data_to_flip){
  temp= data_to_flip
  for (ii in 1:dim(data_to_flip)[2])
    data_to_flip[,ii] = temp[,dim(data_to_flip)[2] - ii + 1]
  
  data_to_flip
}

move_hemispheres<- function(data_to_flip){
  temp= data_to_flip
  data_to_flip[1:180,] = temp[181:360,]
  data_to_flip[181:360,] = temp[1:180,]
  data_to_flip
}
  

## plot IPSL ----

names(data_ipsl_CMIP5)

data_ipsl_CMIP5$to$diff_8p5<- fliplr_matrix(data_ipsl_CMIP5$to$diff_8p5)
data_ipsl_CMIP5$to$diff_8p5<- move_hemispheres(data_ipsl_CMIP5$to$diff_8p5)
data_ipsl_CMIP5$to$fut585_2030<- fliplr_matrix(data_ipsl_CMIP5$to$fut585_2030)
data_ipsl_CMIP5$to$fut585_2030<- move_hemispheres(data_ipsl_CMIP5$to$fut585_2030)

data_ipsl_CMIP5$pp$diff_8p5<- fliplr_matrix(data_ipsl_CMIP5$pp$diff_8p5)
data_ipsl_CMIP5$pp$diff_8p5<- move_hemispheres(data_ipsl_CMIP5$pp$diff_8p5)
data_ipsl_CMIP5$pp$fut585_2030<- fliplr_matrix(data_ipsl_CMIP5$pp$fut585_2030)
data_ipsl_CMIP5$pp$fut585_2030<- move_hemispheres(data_ipsl_CMIP5$pp$fut585_2030)

data_ipsl_CMIP5$phy$diff_8p5<- fliplr_matrix(data_ipsl_CMIP5$phy$diff_8p5)
data_ipsl_CMIP5$phy$diff_8p5<- move_hemispheres(data_ipsl_CMIP5$phy$diff_8p5)
data_ipsl_CMIP5$phy$fut585_2030<- fliplr_matrix(data_ipsl_CMIP5$phy$fut585_2030)
data_ipsl_CMIP5$phy$fut585_2030<- move_hemispheres(data_ipsl_CMIP5$phy$fut585_2030)

data_ipsl_CMIP5$zoo$diff_8p5<- fliplr_matrix(data_ipsl_CMIP5$zoo$diff_8p5)
data_ipsl_CMIP5$zoo$diff_8p5<- move_hemispheres(data_ipsl_CMIP5$zoo$diff_8p5)
data_ipsl_CMIP5$zoo$fut585_2030<- fliplr_matrix(data_ipsl_CMIP5$zoo$fut585_2030)
data_ipsl_CMIP5$zoo$fut585_2030<- move_hemispheres(data_ipsl_CMIP5$zoo$fut585_2030)

titles<-c("Sea surface temperature", "Net primary production","Phytoplankton carbon","Zooplankton carbon")
coltitles<-c("C", "mol m-2 s-1","mol m-2","mol m-2") # check that all units are the same across CMIPs and earth models - transform to more meaningful - e.g. milligrams?
data_ipsl_CMIP5$to$hist$data_units
data_ipsl_CMIP5$pp$hist$data_units
data_ipsl_CMIP5$phy$hist$data_units
data_ipsl_CMIP5$zoo$hist$data_units

color<-list(main_plot_colour_values_tos, main_plot_colour_values_pp, main_plot_colour_values_phyto, main_plot_colour_values_zoo) 
num_dp_variables<-c(0,9,2,2)

map_ipsl585_CMIP5<-list()
map_ipsl585_CMIP5_2030<-list()

for (i in 1:length(data_ipsl_CMIP5)){ 
  
  tit <- paste("IPSL RCP8.5", titles[[i]], "change (1990s vs 2090s)",cmip[1],sep =" ")
  map_ipsl585_CMIP5[[i]]<-plot_FISH_MIP(data_ipsl_CMIP5[[i]]$diff_8p5, tit, delta_plot_colour_values, colour_scheme = colour_scheme2, coltitle = "change \n (%)", model_type = NA)
  names(map_ipsl585_CMIP5)[[i]]<-variable_to_extract[[i]]
  
  tit <- paste("IPSL RCP8.5", titles[[i]], "in 2030", cmip[1], sep =" ")
  map_ipsl585_CMIP5_2030[[i]]<-plot_FISH_MIP(data_ipsl_CMIP5[[i]]$fut585_2030, tit, color[[i]], colour_scheme = colour_scheme4, coltitle = coltitles[[i]], model_type = NA, num_dp = num_dp_variables[[i]])
  names(map_ipsl585_CMIP5_2030)[[i]]<-variable_to_extract[[i]]

  rm(tit)
  
}

names(map_ipsl585_CMIP5)
map_ipsl585_CMIP5$to 
map_ipsl585_CMIP5_2030$to


## plot GFDL ----

names(data_gfdl_CMIP5)

data_gfdl_CMIP5$to$diff_8p5<- fliplr_matrix(data_gfdl_CMIP5$to$diff_8p5)
data_gfdl_CMIP5$to$diff_8p5<- move_hemispheres(data_gfdl_CMIP5$to$diff_8p5)
data_gfdl_CMIP5$to$fut585_2030<- fliplr_matrix(data_gfdl_CMIP5$to$fut585_2030)
data_gfdl_CMIP5$to$fut585_2030<- move_hemispheres(data_gfdl_CMIP5$to$fut585_2030)

data_gfdl_CMIP5$pp$diff_8p5<- fliplr_matrix(data_gfdl_CMIP5$pp$diff_8p5)
data_gfdl_CMIP5$pp$diff_8p5<- move_hemispheres(data_gfdl_CMIP5$pp$diff_8p5)
data_gfdl_CMIP5$pp$fut585_2030<- fliplr_matrix(data_gfdl_CMIP5$pp$fut585_2030)
data_gfdl_CMIP5$pp$fut585_2030<- move_hemispheres(data_gfdl_CMIP5$pp$fut585_2030)

data_gfdl_CMIP5$phy$diff_8p5<- fliplr_matrix(data_gfdl_CMIP5$phy$diff_8p5)
data_gfdl_CMIP5$phy$diff_8p5<- move_hemispheres(data_gfdl_CMIP5$phy$diff_8p5)
data_gfdl_CMIP5$phy$fut585_2030<- fliplr_matrix(data_gfdl_CMIP5$phy$fut585_2030)
data_gfdl_CMIP5$phy$fut585_2030<- move_hemispheres(data_gfdl_CMIP5$phy$fut585_2030)

data_gfdl_CMIP5$zoo$diff_8p5<- fliplr_matrix(data_gfdl_CMIP5$zoo$diff_8p5)
data_gfdl_CMIP5$zoo$diff_8p5<- move_hemispheres(data_gfdl_CMIP5$zoo$diff_8p5)
data_gfdl_CMIP5$zoo$fut585_2030<- fliplr_matrix(data_gfdl_CMIP5$zoo$fut585_2030)
data_gfdl_CMIP5$zoo$fut585_2030<- move_hemispheres(data_gfdl_CMIP5$zoo$fut585_2030)

# coltitles<-c("C", "mol m-2 s-1","mol m-2","mol m-2") 
# check units 
data_gfdl_CMIP5$to$hist$data_units
data_gfdl_CMIP5$pp$hist$data_units
data_gfdl_CMIP5$phy$hist$data_units
data_gfdl_CMIP5$zoo$hist$data_units

map_gfdl585_CMIP5<-list()
map_gfdl585_CMIP5_2030<-list()

for (i in 1:length(data_ipsl_CMIP5)){ 
  
  tit <- paste("GFDL RCP8.5", titles[[i]], "change (1990s vs 2090s)",cmip[1],sep =" ")
  map_gfdl585_CMIP5[[i]]<-plot_FISH_MIP(data_gfdl_CMIP5[[i]]$diff_8p5, tit, delta_plot_colour_values, colour_scheme = colour_scheme2, coltitle = "change \n (%)", model_type = NA)
  names(map_gfdl585_CMIP5)[[i]]<-variable_to_extract[[i]]
  
  tit <- paste("GFDL RCP8.5", titles[[i]], "in 2030", cmip[1], sep =" ")
  map_gfdl585_CMIP5_2030[[i]]<-plot_FISH_MIP(data_gfdl_CMIP5[[i]]$fut585_2030, tit, color[[i]], colour_scheme = colour_scheme4, coltitle = coltitles[[i]], model_type = NA, num_dp = num_dp_variables[[i]])
  names(map_gfdl585_CMIP5_2030)[[i]]<-variable_to_extract[[i]]

  rm(tit)
  
}

names(map_gfdl585_CMIP5)
map_gfdl585_CMIP5$to 
map_gfdl585_CMIP5_2030$to

```

# Model average for CMIP5

```{r}

# you can calculate SD and agreement as in batch_run_maps.R

model_stat<-function(data, variable){

  X <- lapply(data, `[[`, variable)
  X <- lapply(X, function(x) replace(x, !is.finite(x), NA))
  Y <- do.call(cbind, X)
  Y <- array(Y, dim=c(dim(X[[1]]), length(X)))
  model_average_new<-apply(Y, c(1, 2), mean, na.rm = TRUE)

  return(list(model_average = model_average_new))
}

data_average_change_CMIP5<-list()
data_average_value_CMIP5<-list()

names(data_ipsl_CMIP5)

for(i in 1:length(data_ipsl_CMIP5)){
  
  data_average_change_CMIP5[[i]]<-model_stat(list(data_ipsl_CMIP5[[i]], data_gfdl_CMIP5[[i]]), variable = 'diff_8p5')$model_average
  names(data_average_change_CMIP5)[[i]]<-variable_to_extract[[i]]
  
  data_average_value_CMIP5[[i]]<-model_stat(list(data_ipsl_CMIP5[[i]], data_gfdl_CMIP5[[i]]), variable = 'fut585_2030')$model_average
  names(data_average_value_CMIP5)[[i]]<-variable_to_extract[[i]]
  
}

# plot earth models average for all input variables

map_average_change_CMIP5<-list()
map_average_value_CMIP5<-list()

for (i in 1:length(data_average_change_CMIP5)){ 
  
  tit <- paste("Mean % change in", titles[[i]], "RCP 8.5, 1990s to 2090s",cmip[1], sep =" ")
  map_average_change_CMIP5[[i]]<-plot_FISH_MIP(data_average_change_CMIP5[[i]], tit, delta_plot_colour_values, colour_scheme = colour_scheme2, coltitle = "change \n (%)", model_type = NA)
  names(map_average_change_CMIP5)[[i]]<-variable_to_extract[[i]]

  
  tit <- paste("Mean", titles[[i]], "across IPSL and GFDL RCP 8.5, 2030", cmip[1], sep =" ")
  map_average_value_CMIP5[[i]]<-plot_FISH_MIP(data_average_value_CMIP5[[i]], tit, color[[i]], colour_scheme = colour_scheme4, coltitle = coltitles[[i]], model_type = NA, num_dp = num_dp_variables[[i]])
  names(map_average_value_CMIP5)[[i]]<-variable_to_extract[[i]]
  
  rm(tit)
  
}

map_average_change_CMIP5$to
map_average_value_CMIP5$to

```

# save inputs ISIMIP2b temp 

```{r}

data_summaries_CMIP5<-list(data_average_change_CMIP5 = data_average_change_CMIP5, data_average_value_CMIP5 = data_average_value_CMIP5)
map_summaries_CMIP5<-list(map_average_change_CMIP5 = map_average_change_CMIP5, map_average_value_CMIP5 = map_average_value_CMIP5)
save(data_ipsl_CMIP5, data_gfdl_CMIP5, map_ipsl585_CMIP5, map_gfdl585_CMIP5, data_summaries_CMIP5, map_summaries_CMIP5, file = "/Users/camillan/fishmip_outputs/CMIP6vsCMIP5_fig_temp/data_inputs_CMIP5.RData")

```

# Load ISIMIP3b inputs 

```{r}

# CMIP6 data location
directory = "/Users/camillan/fishmip_inputs/marine-fishery_global_ISIMIP3b/"

# extract data IPSL ---- 

variable_to_extract <-c("to", "pp", "phy", "zoo") # just to be consistent with names across cmips and earth models 
variable_to_extract3 <-c("tos", "intpp", "phyc-vint", "zooc-vint")

yearmonth1<- as.yearmon("1990-01")
yearmonth2<- as.yearmon("1999-12") # montly values 

yearmonth1_fut<- as.yearmon("2090-01")
yearmonth2_fut<- as.yearmon("2099-12")

data_ipsl_CMIP6<-list()

for (i in 1:length(variable_to_extract3)){

  filename<-paste0("ipsl-cm6a-lr_r1i1p1f1_historical_", variable_to_extract3[i],"_onedeg_global_monthly_1850_2014.nc")
  
  hist<- averageEnvironmentalCDF(directory, filename , variable_to_extract3[i], yearmonth1, yearmonth2, average_whole_period = TRUE, convert_to_kg_km = FALSE, hist = TRUE, cmip = 6)
  
  filename<-paste0("ipsl-cm6a-lr_r1i1p1f1_ssp126_", variable_to_extract3[i],"_onedeg_global_monthly_2015_2100.nc")
  
  fut126<-averageEnvironmentalCDF(directory, filename , variable_to_extract3[i], yearmonth1_fut, yearmonth2_fut, average_whole_period = TRUE, convert_to_kg_km = FALSE, hist = FALSE, cmip = 6)
  
  filename<-paste0("ipsl-cm6a-lr_r1i1p1f1_ssp585_", variable_to_extract3[i],"_onedeg_global_monthly_2015_2100.nc")
  
  fut585<- averageEnvironmentalCDF(directory, filename , variable_to_extract3[i], yearmonth1_fut, yearmonth2_fut, average_whole_period = TRUE, convert_to_kg_km = FALSE, hist = FALSE, cmip = 6)
  
  fut585_2030<-averageEnvironmentalCDF(directory, filename , variable_to_extract3[i], as.yearmon("2030-01"), as.yearmon("2030-12"), average_whole_period = FALSE, convert_to_kg_km = FALSE, hist = FALSE, cmip = 6) # mean annual temp in 2030
  fut585_2030<-fut585_2030$fishvar[,,1]
  
  diff_2p6 = fut126$fishvar / hist$fishvar * 100 - 100
  diff_8p5 = fut585$fishvar / hist$fishvar * 100 - 100
  
  data_ipsl_CMIP6[[i]]<-list(hist = hist, fut126 = fut126, fut585_2030 = fut585_2030, fut585 = fut585, diff_2p6 = diff_2p6, diff_8p5 = diff_8p5)
  names(data_ipsl_CMIP6)[[i]]<-variable_to_extract[[i]]
  
  rm(hist, fut126, fut585, fut585_2030, diff_2p6, diff_8p5)
 
}

names(data_ipsl_CMIP6)

# calculate data ranges: 
min(data_ipsl_CMIP5$zoo$fut585_2030, na.rm = TRUE)

# extract data GFDL ---- 

data_gfdl_CMIP6<-list()

for (i in 1:length(variable_to_extract3)){

  filename<-paste0("gfdl-esm4_r1i1p1f1_historical_", variable_to_extract3[i],"_onedeg_global_monthly_1850_2014.nc")
  
  hist<- averageEnvironmentalCDF(directory, filename , variable_to_extract3[i], yearmonth1, yearmonth2, average_whole_period = TRUE, convert_to_kg_km = FALSE, hist = TRUE, cmip = 6)
  
  filename<-paste0("gfdl-esm4_r1i1p1f1_ssp126_", variable_to_extract3[i],"_onedeg_global_monthly_2015_2100.nc")
  
  fut126<- averageEnvironmentalCDF(directory, filename , variable_to_extract3[i], yearmonth1_fut, yearmonth2_fut, average_whole_period = TRUE, convert_to_kg_km = FALSE, hist = FALSE, cmip = 6)
  
  filename<-paste0("gfdl-esm4_r1i1p1f1_ssp585_", variable_to_extract3[i],"_onedeg_global_monthly_2015_2100.nc")
  
  fut585<- averageEnvironmentalCDF(directory, filename , variable_to_extract3[i], yearmonth1_fut, yearmonth2_fut, average_whole_period = TRUE, convert_to_kg_km = FALSE, hist = FALSE, cmip = 6)
  
  fut585_2030<-averageEnvironmentalCDF(directory, filename , variable_to_extract3[i], as.yearmon("2030-01"), as.yearmon("2030-12"), average_whole_period = FALSE, convert_to_kg_km = FALSE, hist = FALSE, cmip = 6) # mean annual temp in 2030
  fut585_2030<-fut585_2030$fishvar[,,1]
  
  diff_2p6 = fut126$fishvar / hist$fishvar * 100 - 100
  diff_8p5 = fut585$fishvar / hist$fishvar * 100 - 100
  
  data_gfdl_CMIP6[[i]]<-list(hist = hist, fut126 = fut126,  fut585_2030 = fut585_2030, fut585 = fut585, diff_2p6 = diff_2p6, diff_8p5 = diff_8p5)
  names(data_gfdl_CMIP6)[[i]]<-variable_to_extract[[i]]
  
  rm(hist, fut126, fut585, diff_2p6, diff_8p5, fut585_2030)
 
}

names(data_gfdl_CMIP6)

```

# Plot ISIMIP3b inputs

```{r map CMIP6}

## plot IPSL ----

# same as above - need to run if only considering CMIP6
# titles<-c("Sea surface temperature", "Net primary production","Phytoplankton carbon","Zooplankton carbon")
# coltitles<-c("C", "mol m-2 s-1","mol m-2","mol m-2")
# color<-list(main_plot_colour_values_tos, main_plot_colour_values_pp, main_plot_colour_values_phyto, main_plot_colour_values_zoo) 
# check units
data_ipsl_CMIP6$to$hist$data_units
data_ipsl_CMIP6$pp$hist$data_units
data_ipsl_CMIP6$phy$hist$data_units
data_ipsl_CMIP6$zoo$hist$data_units

map_ipsl585_CMIP6<-list()
map_ipsl585_CMIP6_2030<-list()

for (i in 1:length(data_ipsl_CMIP6)){ 
  
  tit <- paste("IPSL RCP8.5", titles[[i]], "change (1990s vs 2090s)",cmip[2],sep =" ")
  map_ipsl585_CMIP6[[i]]<-plot_FISH_MIP(data_ipsl_CMIP6[[i]]$diff_8p5, tit, delta_plot_colour_values, colour_scheme = colour_scheme2, coltitle = "change \n (%)", model_type = NA)
  names(map_ipsl585_CMIP6)[[i]]<-variable_to_extract[[i]]
  
  tit <- paste("IPSL RCP8.5", titles[[i]], "in 2030", cmip[2], sep =" ") # can change year....
  map_ipsl585_CMIP6_2030[[i]]<-plot_FISH_MIP(data_ipsl_CMIP6[[i]]$fut585_2030, tit, color[[i]], colour_scheme = colour_scheme4, coltitle = coltitles[[i]], model_type = NA, num_dp = num_dp_variables[[i]])
  names(map_ipsl585_CMIP6_2030)[[i]]<-variable_to_extract[[i]]

  rm(tit)
  
}

names(map_ipsl585_CMIP6)
map_ipsl585_CMIP6$to 
map_ipsl585_CMIP6_2030$to

## plot GFDL ----

# need to model hemisphere
# checked: different data layout do not effect the calculation of model mean, SD and agreements because these are done after you flipped the matrix and/or change hemisphere. it does not effect the calculation of trends because you are first weighting biomass by grid cell according to explicit lat values and then you are averaging by lat and long anyway.

data_gfdl_CMIP6$to$diff_8p5<- fliplr_matrix(data_gfdl_CMIP6$to$diff_8p5)
data_gfdl_CMIP6$to$fut585_2030<- fliplr_matrix(data_gfdl_CMIP6$to$fut585_2030)

data_gfdl_CMIP6$pp$diff_8p5<- fliplr_matrix(data_gfdl_CMIP6$pp$diff_8p5)
data_gfdl_CMIP6$pp$fut585_2030<- fliplr_matrix(data_gfdl_CMIP6$pp$fut585_2030)

data_gfdl_CMIP6$phy$diff_8p5<- fliplr_matrix(data_gfdl_CMIP6$phy$diff_8p5)
data_gfdl_CMIP6$phy$fut585_2030<- fliplr_matrix(data_gfdl_CMIP6$phy$fut585_2030)

data_gfdl_CMIP6$zoo$diff_8p5<- fliplr_matrix(data_gfdl_CMIP6$zoo$diff_8p5)
data_gfdl_CMIP6$zoo$fut585_2030<- fliplr_matrix(data_gfdl_CMIP6$zoo$fut585_2030)

map_gfdl585_CMIP6<-list()
map_gfdl585_CMIP6_2030<-list()

for (i in 1:length(data_gfdl_CMIP6)){ 
  
  tit <- paste("GFDL RCP8.5", titles[[i]], "change (1990s vs 2090s)",cmip[2],sep =" ")
  map_gfdl585_CMIP6[[i]]<-plot_FISH_MIP(data_gfdl_CMIP6[[i]]$diff_8p5, tit, delta_plot_colour_values, colour_scheme = colour_scheme2, coltitle = "change \n (%)", model_type = NA)
  names(map_gfdl585_CMIP6)[[i]]<-variable_to_extract[[i]]
  
  tit <- paste("GFDL RCP8.5", titles[[i]], "in 2030", cmip[2], sep =" ") # can change year....
  map_gfdl585_CMIP6_2030[[i]]<-plot_FISH_MIP(data_gfdl_CMIP6[[i]]$fut585_2030, tit, color[[i]], colour_scheme = colour_scheme4, coltitle = coltitles[[i]], model_type = NA, num_dp = num_dp_variables[[i]])
  names(map_gfdl585_CMIP6_2030)[[i]]<-variable_to_extract[[i]]

  rm(tit)
  
}

```

# Model average for CMIP6

```{r}

data_average_change_CMIP6<-list()
data_average_value_CMIP6<-list()

for(i in 1:length(data_ipsl_CMIP6)){
  
  data_average_change_CMIP6[[i]]<-model_stat(list(data_ipsl_CMIP6[[i]], data_gfdl_CMIP6[[i]]), variable = 'diff_8p5')$model_average
  names(data_average_change_CMIP6)[[i]]<-variable_to_extract[[i]]
  
  data_average_value_CMIP6[[i]]<-model_stat(list(data_ipsl_CMIP6[[i]], data_gfdl_CMIP6[[i]]), variable = 'fut585_2030')$model_average
  names(data_average_value_CMIP6)[[i]]<-variable_to_extract[[i]]
  
}

# plot earth models average for all input variables

map_average_change_CMIP6<-list()
map_average_value_CMIP6<-list()

for (i in 1:length(data_average_change_CMIP6)){ 
  
  tit <- paste("Mean % change in", titles[[i]], "RCP 8.5, 1990s to 2090s",cmip[2], sep =" ")
  map_average_change_CMIP6[[i]]<-plot_FISH_MIP(data_average_change_CMIP6[[i]], tit, delta_plot_colour_values, colour_scheme = colour_scheme2, coltitle = "change \n (%)", model_type = NA)
  names(map_average_change_CMIP6)[[i]]<-variable_to_extract[[i]]

  
  tit <- paste("Mean", titles[[i]], "across IPSL and GFDL RCP 8.5, 2030", cmip[2], sep =" ")
  map_average_value_CMIP6[[i]]<-plot_FISH_MIP(data_average_value_CMIP6[[i]], tit, color[[i]], colour_scheme = colour_scheme4, coltitle = coltitles[[i]], model_type = NA, num_dp = num_dp_variables[[i]])
  names(map_average_value_CMIP6)[[i]]<-variable_to_extract[[i]]
  
  rm(tit)
  
}

map_average_change_CMIP6$to
map_average_value_CMIP6$to

```


# save inputs ISIMIP3b temp 

```{r}

data_summaries_CMIP6<-list(data_average_change_CMIP6 = data_average_change_CMIP6, data_average_value_CMIP6 = data_average_value_CMIP6)
map_summaries_CMIP6<-list(map_average_change_CMIP6 = map_average_change_CMIP6, map_average_value_CMIP6 = map_average_value_CMIP6)
save(data_ipsl_CMIP6, data_gfdl_CMIP6, map_ipsl585_CMIP6, map_gfdl585_CMIP6, data_summaries_CMIP6, map_summaries_CMIP6, file = "/Users/camillan/fishmip_outputs/CMIP6vsCMIP5_fig_temp/data_inputs_CMIP6.RData")

```

# Delta plot 

```{r}

# you could calculate delta as scatter plot - as in batch_run_maps.R

# option 1 - subtract (julia) - OK

delta_data<-list()
delta_map<-list()

for(i in 1:length(data_summaries_CMIP6$data_average_change_CMIP6)){
 
  delta_data[[i]]<-data_summaries_CMIP6$data_average_change_CMIP6[[i]] - data_summaries_CMIP5$data_average_change_CMIP5[[i]]
  names(delta_data)[[i]]<-variable_to_extract[[i]]
  
  tit<-paste("Delta (CMIP6 change - CMIP5 change)", titles[[i]], sep =" ")
  delta_map[[i]]<-plot_FISH_MIP(delta_data[[i]], tit, delta_plot_colour_values, colour_scheme = colour_scheme3, coltitle = "Difference \nin (%) \nchange \n")  
  names(delta_map)[[i]]<-variable_to_extract[[i]]
  
}

names(delta_map)

```


# Put all maps together 

```{r multipanel plot}

library(patchwork)

# FIG 1 inputs
# change between 1990 and 2090s for CMIP5 and form CMIP6 and delta between CMIPs 

layout <- "
ABC
DEF
GHK
LMN
"

pt<-map_average_change_CMIP5$to + map_average_change_CMIP6$to + delta_map$to +
  map_average_change_CMIP5$pp + map_average_change_CMIP6$pp + delta_map$pp +
  map_average_change_CMIP5$phy + map_average_change_CMIP6$phy + delta_map$phy +
  map_average_change_CMIP5$zoo + map_average_change_CMIP6$zoo + delta_map$zoo +
  plot_layout(design = layout)

pdf(paste0(save_loc,"Fig1.pdf"), height=15, width=20)
pt 
dev.off()


# FIG 1B or S1? Inpu values 
layout <- "
AB
CD
EF
GH
"

pt<-map_average_value_CMIP5$to + map_average_value_CMIP6$to +
  map_average_value_CMIP5$pp + map_average_value_CMIP6$pp + 
  map_average_value_CMIP5$phy + map_average_value_CMIP6$phy + 
  map_average_value_CMIP5$zoo + map_average_value_CMIP6$zoo + 
  plot_layout(design = layout)

pdf(paste0(save_loc,"Fig1B.pdf"), height=15, width=15)
pt 
dev.off()



```




