---
title: "Plotting global models outputs"
author: "Camilla Novaglio"
date: "04/11/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Load libraries for netcdf and define variables

```{r load CMIP5}

rm(list=ls())
library(grid)
library(zoo)
library(viridis)
library(tidyr)
library(dplyr)
library(ncdf4)
library(zoo)

source("/Users/nov017/R-projects/CMIP5vsCMIP6/R/HelperScripts.r")
source("/Users/nov017/R-projects/CMIP5vsCMIP6/R/Funcs_maps.r")
source("/Users/nov017/R-projects/CMIP5vsCMIP6/R/Funcs_maps_crops.r")

# load fishmip data 
load("/Users/nov017/fishmip_outputs/CMIP6vsCMIP5_fig_temp/model_average_all_CMIP5.RData")
model_average_all_CMIP5_fish<-model_average_all_CMIP5

```

# load libraries for plotting and define criteria 

```{r}

# Define color/legend limits 
main_plot_colour_values = c(0,10000) # these need to change for each model? 
delta_plot_colour_values = c(-50,50)
model_agreement_plot_colour_values = c(50,100)

# define a color scheme 
colour_scheme1 <- c(low = 'white', mid = "skyblue1",  high = 'royalblue1')
colour_scheme2 <- c(low = 'red', mid = "white",  high = 'royalBlue1')

# Download and process world outline
library(sf)
library(rnaturalearth)
world <- ne_countries(scale = "medium", returnclass = "sf")
robCRS <- CRS("+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs")
world_sf <- st_transform(world, crs = st_crs(robCRS)) # Convert to different CRS

```


```{r}

#  lat X lon (0.5 res.) X 2 types of projections? so pick one 
i=2 # ir = 1; rf = 2

# crops nc 
barley <- nc_open("/Users/nov017/Dropbox/crop change gridded/yldchange.barley.rcp8p5.noco2.2050.nc4")
barley <- ncvar_get(barley, "mean_yldchange")[, ,i] 
# decreases in USA - no  canada

cotton_nc <- nc_open("/Users/nov017/Dropbox/crop change gridded/yldchange.cotton.rcp8p5.noco2.2050.nc4")
cotton <- ncvar_get(cotton_nc, "mean_yldchange")[, ,i]  
# mixed in USA but mostly  decreases - no canada
# increases in north europe

maize <- nc_open("/Users/nov017/Dropbox/crop change gridded/yldchange.maize.rcp8p5.noco2.2050.nc4")
maize <- ncvar_get(maize, "mean_yldchange")[, ,i] 
# huge increases in canada and north europe - this is very similar to the final  global map! 

rapeseed <- nc_open("/Users/nov017/Dropbox/crop change gridded/yldchange.rapeseed.rcp8p5.noco2.2050.nc4")
rapeseed <- ncvar_get(rapeseed, "mean_yldchange")[, ,i] 
# mostly decreases, some increases in very high lat region close to the pole

rice <- nc_open("/Users/nov017/Dropbox/crop change gridded/yldchange.rice.rcp8p5.noco2.2050.nc4")
rice <- ncvar_get(rice, "mean_yldchange")[, ,i]  

sorghum <- nc_open("/Users/nov017/Dropbox/crop change gridded/yldchange.sorghum.rcp8p5.noco2.2050.nc4")
sorghum <- ncvar_get(sorghum, "mean_yldchange")[, ,i] 

soy <- nc_open("/Users/nov017/Dropbox/crop change gridded/yldchange.soy.rcp8p5.noco2.2050.nc4")
soy <- ncvar_get(soy, "mean_yldchange")[, ,i]  

wheat <- nc_open("/Users/nov017/Dropbox/crop change gridded/yldchange.wheat.rcp8p5.noco2.2050.nc4")
wheat <- ncvar_get(wheat, "mean_yldchange")[, ,i] 

# map one crpo to try 
tit = "cotton"
trial<-plot_FISH_MIP_crop(wheat, tit, delta_plot_colour_values, colour_scheme = colour_scheme2, coltitle = "Biomass \n Change \n (%)", model_type = "DBEM")
trial
# dark blue due to increases in: maize, rice and soy.. and weath but to a lesser extent


# pdf("/Users/nov017/Desktop/trial.pdf", height=5, width=5)
# trial
# dev.off()

```

# Model average for CMIP5

```{r}

data = list(barley = barley, cotton = cotton, maize = maize, rapeseed = rapeseed, rice = rice, sorghum = sorghum, soy = soy, wheat = wheat)

model_stat<-function(data){
  
  # X <- lapply(data, `[[`, 'diff_8p5')
  X <- data 
  # X <- lapply(X, function(x) replace(x, !is.finite(x), NA))
  Y <- do.call(cbind, X)
  Y <- array(Y, dim=c(dim(X[[1]]), length(X)))
  model_average_new<-apply(Y, c(1, 2), mean, na.rm = TRUE)
  
  # model_sd_new<-apply(Y, c(1, 2), sd, na.rm = TRUE)
  # 
  # # X <- lapply(data, `[[`, 'diff_8p5')
  # X <- data 
  # Y <- do.call(cbind, X)
  # Y <- array(Y, dim=c(dim(X[[1]]), length(X)))
  # 
  # #  this takes into account agreement on both positive or negative changes. - i.e. if most models show positive change agreement will be high and vice versa. 
  # temp<-apply(Y, c(1,2), function(x) ifelse(sum(is.na(x)>0), NA, length(x[which(x>0)]))) # sum the number of values that are >0 - including inf
  # temp2<-apply(Y, c(1,2), function(x) length(x[which(!is.na(x))])) # sum the number of values that are different from na and nan - including inf
  # temp4<-temp/temp2
  # model_agreement_new<-ifelse(is.na(temp4), NA, ifelse(temp4>0.5, temp4*100, (1-temp4)*100)) 
  # 
  # return(list(model_average = model_average_new, model_sd = model_sd_new, model_agreement = model_agreement_new))
  
  return(model_average = model_average_new)
}

model_average_ipsl_CMIP5_crop<-model_stat(data)
# check e.g cell 1, 43 = 7229 - OK
model_average_ipsl_CMIP5_crop[1,43]
barley[1,43]
cotton[1,43]
maize[1,43] 
rapeseed[1,43]
rice[1,43]
sorghum[1,43]
soy[1.43]
wheat[1,43]

# Define a layout function
mean_plot_colour_values = c(-50,50)
sd_plot_colour_values = c(0,50)
model_agreement_plot_colour_values = c(50,100)

# Plot the model average CROP
maptitle_average = paste("Mean % change across crops, IPSL RCP 8.5 CMIP5", sep=" ")
avarage_CMIP5_ipsl_crop<-plot_FISH_MIP_crop(model_average_ipsl_CMIP5_crop, maptitle_average, mean_plot_colour_values, colour_scheme = colour_scheme2, coltitle = "Change \n(%)",model_type = "DBEM")

# Plot the model average FISH
maptitle_average = paste("Mean % change across ocean biomass, IPSL RCP 8.5 CMIP5", sep=" ")
avarage_CMIP5_ipsl_fish<-plot_FISH_MIP(model_average_all_CMIP5_fish, maptitle_average, mean_plot_colour_values, colour_scheme = colour_scheme2, coltitle = "Change \n(%)")

```

```{r}

# MAKE SURE THAT ALL MATRICES ARE ON ONE DEGREE SCALE

lons_to_use = seq(1,719,2)
lats_to_use = seq(1,359,2)

model_average_ipsl_CMIP5_crop_reduced = model_average_ipsl_CMIP5_crop[lons_to_use, lats_to_use]
model_average_ipsl_CMIP5_crop_reduced = model_average_ipsl_CMIP5_crop[lons_to_use, lats_to_use]

# also check resolution
lon <- ncvar_get(cotton_nc, "lon") # -179.75 
lat <- ncvar_get(cotton_nc, "lat") # 89.75

# fishmip is 
trial<-nc_open("/Users/nov017/fishmip_outputs/marine-fishery_global_ISIMIP2b/BOATS/ipsl-cm5a-lr/future/boats_ipsl-cm5a-lr_nobc_rcp4p5_wo-diaz_fishing_no-oa_tcb_global_monthly_2006_2099.nc4")
lon <- ncvar_get(trial, "lon") # -179.5 
lat <- ncvar_get(trial, "lat") # 89.5

# combine 
# but empty land needs to remain empty land... (NaN + NaN = 0!)
dim(model_average_ipsl_CMIP5_crop_reduced)
image(model_average_all_CMIP5_fish)
model_average_ipsl_CMIP5_crop_reduced[1,180]
model_average_all_CMIP5_fish[1,180]
sum(NA, NA, na.rm=TRUE)

X <- list(model_average_ipsl_CMIP5_crop_reduced = model_average_ipsl_CMIP5_crop_reduced, model_average_all_CMIP5_fish = model_average_all_CMIP5_fish)
X <- lapply(X, function(x) replace(x, !is.finite(x), NA))
Y <- do.call(cbind, X)
Y <- array(Y, dim=c(dim(X[[1]]), length(X)))
# model_average_new<-apply(Y, c(1, 2), sum, na.rm = TRUE) # BUT
model_average_new<-apply(Y, c(1, 2), function(x) ifelse(is.na(x[1]) & is.na(x[2]), NA, sum(x[1], x[2], na.rm=TRUE)))

# image(model_average_ipsl_CMIP5_crop_reduced)
# image(model_average_all_CMIP5_fish)
# image(model_average_new)

# # check cell - not OK
# model_average_ipsl_CMIP5_crop_reduced[1,43]
# model_average_all_CMIP5_fish[1,43]
# model_average_new[1,43]
# model_average_new[1,180]

# plot
# define title IPSL
maptitle_average = paste("Mean % change across crops and ocean biomass, IPSL RCP 8.5 CMIP5", sep=" ")

# Plot the model average
avarage_CMIP5_ipsl_crops_fish<-plot_FISH_MIP_crop(model_average_new, maptitle_average, mean_plot_colour_values, colour_scheme = colour_scheme2, coltitle = "Change \n(%)")

```

```{r}

library(patchwork)

# option 1 all together 
tiff("/Users/nov017/Dropbox/CMIP5vsCMIP6/figs/crops/crops_fish_map1_mapping_rf.tiff", height=4, width=7, units ='in', res=300)
avarage_CMIP5_ipsl_crops_fish
dev.off()

jpeg("/Users/nov017/Dropbox/CMIP5vsCMIP6/figs/crops/crops_fish_map1_mapping_rf.jpeg", height=4, width=7, units = "in", res = 300)
avarage_CMIP5_ipsl_crops_fish
dev.off()

pdf("/Users/nov017/Dropbox/CMIP5vsCMIP6/figs/crops/crops_fish_map1_mapping_rf.pdf", height=4, width=15)
avarage_CMIP5_ipsl_crops_fish
dev.off()

# NOTE  - need to change plotting code - land on top of data; size = 0.05, color = grey80 
# option 2 land and water 
tiff("/Users/nov017/Dropbox/CMIP5vsCMIP6/figs/crops/crops_fish_map2_mapping_rf.tiff", height=4, width=15, units ='in', res=300)
avarage_CMIP5_ipsl_crop + avarage_CMIP5_ipsl_fish
dev.off()

jpeg("/Users/nov017/Dropbox/CMIP5vsCMIP6/figs/crops/crops_fish_map2_mapping_rf.jpeg", height=4, width=15, units = "in", res = 300)
avarage_CMIP5_ipsl_crop + avarage_CMIP5_ipsl_fish
dev.off()

pdf("/Users/nov017/Dropbox/CMIP5vsCMIP6/figs/crops/crops_fish_map2_mapping_rf.pdf", height=4, width=15)
avarage_CMIP5_ipsl_crop + avarage_CMIP5_ipsl_fish 
dev.off()


```



